- faulty oracle
- punk protocol
- cosmos
- call injection
- internal book-keeping
- vulcan forged
- bt finance
- inconsistent access control
- akropolis
- data leak
- bzx
- bitcoinica
- pancakehunny
- sushi
- layer-0
- opyn
- flash loan
- vee finance
- saddle finance
- chainswap
- thorchain
- growth defi
- cream finance
- bridge
- layer 0
- hyperledger
- indexed finance
- upbit
- value defi
- black hat
- elephant money
- alchemix
- code injection
- fulcrum
- furucombo
- dragonex
- beanstalk farms
- paid network
- pancakebunny
- soft yearn
- starstream finance
- klayswap
- binance
- zaif
- easyfi
- rollup
- faulty api
- polkadot
- absence of coding logic or sanity check
- pnetwork
- gatehub
- profit calculation error
- bitgrail
- interoperability
- malicious
- fei protocol
- venus protocol
- dao maker
- bearn fi
- cashaa
- bitrue
- merlin lab
- xtoken
- compromised private key-wallet
- one ring finance
- security audit
- direct call to untrusted contract
- unsafe or infinite token approval
- bitpoint
- overledger
- yapizon
- interoperability solution
- autoshark finance
- memory error
- coincheck
- meter
- token
- poly network
- phishing
- audius
- poly network
- bitcash
- btc markets
- hyperledger cactus
- maplechange
- malware
- on-chain oracle manipulation
- ascendex
- origin protocol
- bitfloor
- inverse finance
- monox
- slowmist
- grim finance
- unsafe multsignature strategy
- deployment mistake
- poloniex
- localbitcoins
- wild credit
- whales
- levyathan
- hyperledger firefly
- burgerswap
- coinsecure
- bitstamp
- unsafe internal state management
- iron finance
- majority attack
- deus finance
- integer overflow or underflow
- spartan protocol
- li finance
- interoperability project
- bad actor
- arithmetic mistakes
- ronin network
- coinbene
- zabu finance
- balancer
- unhandled or mishandled exception
- layer 2
- deprecated function
- gatecoin
- acala
- integration
- incompatibility between model and token
- fantasm
- alpha finance lab
- dego finance
- vulnerability
- kusama
- bitfinex
- cashio
- pizza defi
- oracle manipulation
- crypto.com
- safedollar
- coinmama
- dodo
- lendf.me/dforce
- certik
- security
- uniswap
- cover protocol
- chainlink
- yearn finance
- roll
- qubit
- force dao
- harvest finance
- malicious oracle updater
- visor finance
- peckshield
- reentrancy
- layer-2
- white hat
- wonderhero
- bondly finance
- badgerdao
- l2
- validation error
- rari capital
- altsbit
- bithumb
- eleven finance
- mt. gox
- mintpal
- 8ight finance
- loom
- unrestricted action
- blockchain
- tinyman
- rug pull
- governance attack
- turtledex
- bter
- security concern
- sandwiching
- liquid
- hybrix
- unprotected function
- horizon bridge
- popsicle finance
- kucoin
- etherdelta
- pickle finance
- uranium finance
- other coding mistake
- warp finance
- nomad bridge
- lympo
- umbrella network
- security risk
- shapeshift
- bitmart
- compound finance
- calculation error
- hack
- external market manipulation
- wormhole
- impossible finance
- transaction order dependency
- treasure dao
- insider trade or other activities
- inconsistent access control
- unsecured oracle
- exmo
- belt finance
- livecoin
- exploit
- meerkat finance
- eminence
- crypto
- unfair slippage protection
- arbitrage whales
